### PR TITLE
chore: modify code to recreate my issue

### PR DESCRIPTION
**Pull request by dev-rgupta**
i have added error msg in readme file

### CODE REVIEW

**Comment by bethesque** [comment]
Hi @dev-rgupta. Can you give me some more information about this PR?

**Comment by dev-rgupta** [comment]
Hi @bethesque,

Basically, this example explained how we can create and verify your pact against Provider API.
I also able to do the same with single pact interaction but I'm not able to do the same thing with a bunch of interactions simultaneously like in **script/consumer-create-pact.sh**  Script there are few statements that are applicable on single interaction 
# set up interaction
curl -X POST -H "X-Pact-Mock-Service: true" -d@script/consumer-interaction.json localhost:1234/interactions

# execute interaction
curl localhost:1234/foo

so My query is How these statements apply to a bunch of interactions like in my pact JSON file I have more than 10 interactions so how can I register all in one go.

**Comment by bethesque** [comment]
This codebase is used for recreating issues so that we can fix bugs. What is your overall goal here? Most people don't interact directly with the mock service, as there is native language support in the languages that use the standalone mock service library. Are you unable to use an existing library?

**Comment by YOU54F** [comment]
Hi @dev-rgupta,

Closing down this PR, if you still have an issue, please feel raise to reach out at slack.pact.io

I noted in your error message, it mentions a swagger parser and I recently noted this repo you created, not taken a deep look but looks really interesting

https://github.com/dev-rgupta/pact-openapi-core

**Pull request closed without merging**
